### ISSUE TITLE
How to get expected pA length of all genes of each 10 grouped neighboring cells?

### ISSUE THREAD

**Issue by 31474molly** [LuChenLab/SCAPE#10]
I'm wondering how to get expected pA length of all genes of each 10 grouped neighboring cells just like Figure 6D in your article? I haven't found a tutorial in git-hub.
Thanks!!

**Comment by zhou-ran** [comment]
Hi, 

Thanks for your interest on our work, this function was not included in our package, and please refer to the `Expected pA length` section in the method.

Ran
