### ISSUE TITLE
pipeline issue for SCAPE toy example

### ISSUE THREAD

**Issue by Shaoyi-Zhang96** [LuChenLab/SCAPE#2]
Hi, 

When I was running the example tool on ubuntu linux python3, I encountered issues with error code "unexpected end of file" when using command:

zcat Mus_musculus.GRCm38.88.gtf.gz | bedtools sort -i /dev/stdin  | bgzip > Mus_musculus.GRCm38.88.gtf.gz

Zcat works fine if applied along but when the pipeline code is used together it shows the error code. 

The data I downloaded was the newer version (Mus_musculus.GRCm39.105.chr.gtf). I tried to run the rest of the preprocessing codes after zcat but it shows error code "start larger than end" so I did not find a way to work around the pipeline. 

Could you please provide any insights into the issue?

Thanks, 
Shaoyi

**Comment by zhou-ran** [comment]
Hi Shaoyi,

I'm sorry for misguiding of command, and I updated the code for sorting gtf file in the wiki page, here is the new command:

```
zcat Mus_musculus.GRCm38.88.gtf.gz | bedtools sort -i /dev/stdin | bgzip > Mus_musculus.GRCm38.88.sorted.gtf.gz

python SCAPE/main.py prepare \
--gtf Mus_musculus.GRCm38.88.sorted.gtf.gz \
--prefix GRCm38
```

I download the newer version gtf from http://ftp.ensembl.org/pub/release-105/gtf/mus_musculus/Mus_musculus.GRCm39.105.chr.gtf.gz, the code worked fine on machine.

Hope this will be helpful to you,

Cheers,
Ran

**Comment by Shaoyi-Zhang96** [comment]
Thank you so much!

**Comment by Shaoyi-Zhang96** [comment]
For the APA inference part, I encountered some problems but resolved them. These are just some minor issues with path and python version -  I just thought it might be helpful if I discuss it with you 【1. changing python - python3. 2. adding SCAPE into path information (or deleting SCAPE from SCAPE/main.py) so the files are read under the same path. 
 
The revised code is as following: 

python3 SCAPE/main.py apamix \
--bed SCAPE/example_data/GRCm38_utr.bed \
--bam SCAPE/example_data/chr1.bam \
--cb SCAPE/example_data/barcode.tsv \
-o ./tutorial \
--tag CB,UR \
--cores 4

Thank you!

**Comment by zhou-ran** [comment]
Thanks for your valuable feedback.
