### ISSUE TITLE
No pasite.csv.gz file in output

### ISSUE THREAD

**Issue by maximumko** [LuChenLab/SCAPE#3]
Hi Ran,
I've tried to run the toy pipeline of SCAPE with the newest gtf file, which is Mus_musculus.GRCm39.105.chr.gtf.gz. However, after sorting and prefixing it, it gave me four empty folders but without pasite.csv.gz when I applied main.py apamix to it. I don't know what happened. Thank you! 

Best,
Max

______________________________
Here are the scripts.
zcat Mus_musculus.GRCm39.105.chr.gtf.gz | bedtools sort -i /dev/stdin  | bgzip > Mus_musculus.GRCm39.105.chr.sorted.gtf.gz

python SCAPE/main.py prepare \
--gtf Mus_musculus.GRCm39.105.chr.sorted.gtf.gz \
--prefix GRCm39

#SCAPE_apamix:
pythonSCAPE/main.py apamix \
--bed GRCm39_utr.bed \
--bam chr1.bam \
--cb barcode.tsv \
-o ./tutorial \
--tag CB,UR \
--cores 4

**Comment by zhou-ran** [comment]
Hi Max,

I guess there is a 'chr' prefix in your gtf file. Because the name of chromosome from chr1.bam don't start with 'chr',  SCAPE can't find any correct regions in chr1.bam and output with nothing. 

I will update a tip for this situation in wiki page.

Have a nice day,
Ran

**Comment by maximumko** [comment]
Hi Ran,
Thank you for the tip.
However, I checked the gtf file and I found that there is no chr prefix in the gtf file. I'm afraid it's still not working.

Another similar issue here, when I tried to analyze the pbmc test sample, the algorithm stuck in the processing with ChrMT and came out with nearly 14,000 pickle files in the tmp folder but still no pasite.csv.gz file.

_________________________________________________________________________________________
head Mus_musculus.GRCm39.105.chr.gtf
>#!genome-build GRCm39
#!genome-version GRCm39
#!genome-date 2020-06
#!genome-build-accession GCA_000001635.9
#!genebuild-last-updated 2021-08
1       havana  gene    150956201       150958296       .       +       .       gene_id "ENSMUSG00000102628"; gene_version "2"; gene_name "Gm37671"; gene_source "havana"; gene_biotype "TEC";
1       havana  transcript      150956201       150958296       .       +       .       gene_id "ENSMUSG00000102628"; gene_version "2"; transcript_id "ENSMUST00000193198"; transcript_version "2"; gene_name "Gm37671"; gene_source "havana"; gene_biotype "TEC"; transcript_name "Gm37671-201"; transcript_source "havana"; transcript_biotype "TEC"; tag "basic"; transcript_support_level "NA (assigned to previous version 1)";


#apamix log
......
2022-03-10 09:59:50.813 | DEBUG    | apamix.inference:run:220 - Processing 1, 24762622, 24766301, +
/home/maximumko/biosoft/SCAPE/apamix/EM.py:443: RuntimeWarning: invalid value encountered in multiply
  ZZ = Z * log_zmat
2022-03-10 10:00:08.388 | DEBUG    | apamix.inference:run:254 - Done! MT, 11297707, 11303500, +
2022-03-10 10:00:40.913 | DEBUG    | apamix.inference:run:254 - Done! MT, 24762622, 24766301, +
#(2022-03-10 10:00:40.919 | INFO     | cli.apamix:apamix:183 - Concating your final sheet) It supposed to contain these two lines.
#(2022-03-10 10:00:40.926 | INFO     | cli.apamix:apamix:200 - All done) But in my pbmc samples running, the algorithm stuck and it didn't return INFO.

**Comment by zhou-ran** [comment]
Hi Max,
Could your give me all commands for testing pbmc samples?

**Comment by maximumko** [comment]
Hi Ran,
Unfortunately yes, I also tested the gtf without 'chr' prefix while it still not working.

Regarding the pbmc data, I understand that the algorithm will be sometimes slow due to the high depth or the long 3'UTR sequence. I tried to wait for it to respond but there was no feedback even after 2 hours. I uploaded my commands below and please help me check whether something goes wrong.

Best,
Max

_________________________________________________________________________________

#pbmc_samples_run_maximumko
wget https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_v3/pbmc_1k_v3_possorted_genome_bam.bam
wget https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_v3/pbmc_1k_v3_possorted_genome_bam.bam.bai
wget https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_v3/pbmc_1k_v3_filtered_feature_bc_matrix.tar.gz
wget ftp://ftp.ensembl.org/pub/release-93/gtf/homo_sapiens/Homo_sapiens.GRCh38.93.gtf.gz
tar -xzvf pbmc_1k_v3_filtered_feature_bc_matrix.tar.gz

zcat Homo_sapiens.GRCh38.93.gtf.gz | bedtools sort -i /dev/stdin | bgzip > Homo_sapiens.GRCh38.93.sorted.gtf.gz

python SCAPE/main.py prepare
--gtf omo_sapiens.GRCh38.93.sorted.gtf.gz
--prefix GRCh38

#SCAPE_apamix:
pythonSCAPE/main.py apamix
--bed GRCh38_utr.bed
--bam pbmc_1k_v3_possorted_genome_bam.bam
--cb filtered_matrix_barcode.tsv.gz
--cores 12 \
--out pbmc1k/ \

#Everything went perfect until the tool run into processing the ChrMT. It just stuck with no error message.
Please let me know if you need anything else. Thanks!

**Comment by zhou-ran** [comment]
Hi Max,

Before processing pbmc dataset, we should make sure that we can get through the toy dataset.

I test the toy code in new linux machine, and everything is OK. Here is code

```
git clone https://github.com/LuChenLab/SCAPE.git

conda create -n scape python=3.7.3

conda source activate scape

pip install -r SCAPE/requirements.txt

cd SCAPE

python main.py apamix \
--bed example_data/GRCm38_utr.bed \
--bam example_data/chr1.bam \
--cb example_data/barcode.tsv \
-o ./tutorial \
--tag CB,UR \
--cores 12

```

**Comment by maximumko** [comment]
Hi Ran,
I tried to use your code in a brand new linux machine and it worked with the default GRCm38_utr.bed. Meanwhile, I also downloaded the Mus_musculus.GRCm38.93.gtf.gz to generate the bed file. It also worked. 
However, it failed again when I applied this code to the new bed file generated by Mus_musculus.GRCm39.105.chr.gtf.gz. I double-checked the prefix and there is no "chr" in front of the chromosome number.

I think the reason is the version difference between Mus_musculus.GRCm38.88.gtf.gz or 38.93 and Mus_musculus.GRCm39.105.gtf.gz.

Here is the output. 

Thank you!

#bed file generated from Mus_musculus.GRCm39.105.gtf.gz, without pasite.csv.gz file.
(scape) max@LAPTOP-RSEO2516:~/SCAPE$ python main.py apamix --bed GRCm39_utr.bed --bam example_data/chr1.bam --cb example_data/barcode.tsv -o ./test --tag CB,UR --cores 12
2022-03-10 17:44:24.808 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, 1_9788847_9795575_-
2022-03-10 17:44:24.808 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, 1_15779709_15793974_+
2022-03-10 17:44:24.808 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, 1_17695059_17701163_+
2022-03-10 17:44:24.808 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, 1_33831217_33842694_-
....
2022-03-10 17:44:56.676 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, X_159584388_159591687_-
2022-03-10 17:45:01.029 | INFO     | cli.apamix:apamix:197 - Concating your final sheet
2022-03-10 17:45:01.068 | INFO     | cli.apamix:apamix:214 - All done

#bed file generated from Mus_musculus.GRCm38.93.gtf.gz, with pasite.csv.gz file.
(scape) max@LAPTOP-RSEO2516:~/SCAPE$ python main.py apamix --bed GRCm38_utr.bed --bam example_data/chr1.bam --cb example_data/barcode.tsv -o ./test --tag CB,UR --cores 12
2022-03-10 17:58:44.630 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, X_143791235_143797796_+
2022-03-10 17:58:44.630 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, X_143855842_143863607_-
2022-03-10 17:58:44.631 | INFO     | cli.apamix:apamix:171 - Skip more than 6000 UTR, X_160801392_160808691_-
/home/max/SCAPE/apamix/apamix.py:342: RuntimeWarning: divide by zero encountered in log
  axis=1
/home/max/SCAPE/apamix/apamix.py:354: RuntimeWarning: divide by zero encountered in log
  axis=1
2022-03-10 17:58:52.649 | DEBUG    | apamix.inference:run:222 - Processing 1, 13564698, 13566396, -
/home/max/SCAPE/apamix/EM.py:443: RuntimeWarning: invalid value encountered in multiply
  ZZ = Z * log_zmat
/home/max/SCAPE/apamix/apamix.py:342: RuntimeWarning: divide by zero encountered in log
  axis=1
...
2022-03-10 18:01:25.550 | DEBUG    | apamix.inference:run:256 - Done! 1, 11297708, 11303681, +
2022-03-10 18:01:25.608 | INFO     | cli.apamix:apamix:197 - Concating your final sheet
2022-03-10 18:01:25.668 | INFO     | cli.apamix:apamix:214 - All done

**Comment by zhou-ran** [comment]
Hi Max,

Chr1.bam was simulated based GRCm38 annotation, and i tried to fetch reads from Chr1.bam using  bed file generated by GRC39, but i didn't get anything.
