### ISSUE TITLE
The process is sleeping

### ISSUE THREAD

**Issue by maximumko** [LuChenLab/SCAPE#4]
Hi Ran!
The main process with apamix, went to sleeping when it run into the final parts. It just showed `2022-03-19 12:06:30.240 | DEBUG    | apamix.inference:run:256 - Done! chrX, 78125790, 78129295, +`. And there is no logger_info like "Concating your final sheet". 

I used `ps aux` to see what happened and the status of this process was Sl+, which means it's sleeping. I don't know how to rewake it or what is the reason led to this situation.

I've tried the toy sample and everything was fine. However, when I applied SCAPE to the samples, 2.87GB or bigger, downloaded from 10x datasets, the process stuck, and went to sleep.

Here is the code:
```
python SCAPE/main.py apamix \
--bed refGenome/GRCh38_utr.bed \
--bam Targeted_SC3v3_Human_Glioblastoma_Neuroscience_possorted_genome_bam.bam \
--out test/results/ \
--cores 12 \
--cb filtered_feature_bc_matrix/barcodes.tsv.gz 
```

**Comment by verohan** [comment]
I have encountered a similar problem. Has this problem been solved?
