### ISSUE TITLE
Error preparing

### ISSUE THREAD

**Issue by cnk113** [LuChenLab/SCAPE#5]
Hello,

I'm trying to prepare my annotation, but there is an error:
```
pybedtools.helpers.BEDToolsError:
Command was:

	bedtools sort -i /tmp/pybedtools.acvu1r7m.tmp

Error message was:
Error: malformed BED entry at line 119. Start was greater than end. Exiting.
```
Any ideas on how to get through this?

**Comment by zhou-ran** [comment]
Hi Chang,

Try to replace bedtools into version 2.26.0 in current shell environment

Hope this helps

Ran

**Comment by cnk113** [comment]
Hey Rab,

I changed the bedtools version and it stills gives the same error.

**Comment by zhou-ran** [comment]
Hi,

That's weird. SCAPE with bedtools (2.26.0) and pybedtools(0.8.1) work fine in different linux server.

**Comment by cnk113** [comment]
Thanks for all the help!
One more thing, how is the intron output used in the recent update?

**Comment by zhou-ran** [comment]
Hi, 

The intron file was used to call the intronic pA sites, and the old intronic bed was six columns format. 
I updated the code to output four columns format for keeping consistent with UTR output.

**Comment by cnk113** [comment]
Sorry to reopen this issue, but I'm getting a lot divide by zero and invalid error in multiply errors during apamix.
```  all_win_log_lik_mat[:, i] = np.log(                                                                                                                                                                                                        [0/1944]
/home/chang/SCAPE/apamix/EM.py:473: RuntimeWarning: divide by zero encountered in log
  log_zmat[:, k] = np.log(ws[k]) + \
/home/chang/SCAPE/apamix/apamix.py:339: RuntimeWarning: divide by zero encountered in log
  all_win_log_lik_mat[:, i] = np.log(
/home/chang/SCAPE/apamix/apamix.py:351: RuntimeWarning: divide by zero encountered in log
  all_win_log_lik_mat[:, i] = np.log(
/home/chang/SCAPE/apamix/apamix.py:368: RuntimeWarning: divide by zero encountered in log
  all_win_log_lik_mat[:, i] = np.log(
```
It's still continuing through these warnings, it's ok to ignore?

**Comment by zhou-ran** [comment]
Yes, it's OK

**Comment by cnk113** [comment]
Thanks!
