### ISSUE TITLE
0 Abundance of PAS in the pasite.csv

### ISSUE THREAD

**Issue by maximumko** [LuChenLab/SCAPE#7]
Hi Ran,
I applied the pipeline to my data successfully, but when I checked the output file, I found that the abundances of the PASs located on chr1-22 are zero, mostly. And the abundance of the PASs located on chrM seems to be correct. 

`(base) scape@instance-1:/home/scape/ref/EA/outs/results$ zcat pasite.csv.gz | grep chr1 | tail -n 1
chr19:61226146:9:-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0`
`(base) scape@instance-1:/home/scape/ref/EA/outs/results$ zcat pasite.csv.gz | tail -n 1
chrM:15303:36:+,5,8,0,7,12,24,28,1,5,2,2,82,13,8,5,0,8,2,1,1,4,9,13,4,6,8,1,31,67,11,17,5,41,1,4,11,42,5,14,21,2,12,9,9,3,5,11,7,4,26,0,50,1,5,11,44,8,1,4,28,12,8,5,0,6,5,15,3,35,7,60,5,18,7,27,3,119,5,6,40,5,82,11,1,4,12,23,80,4,11,3,1,35,17,5,3,4,9,5,1,1,4,5,7,11,1,8,1,2,4,4,0,4,0,3,8,16,1,11,5,5,27,7,2,29,32,8`

I tried to use a different version of gtf file to generate the utr_bed file, but it didn't work. I wonder that is there any solution to figure out what happened or how to fix it? 
Thank you!

Max

**Comment by zhou-ran** [comment]
Hi Max,


I guess the cell barcodes which you provided for scape were low quality cells and most rna fragments from the given cells were assigned to mitochondria.

Could you feed the cells after quality control (like Seurat) into SCAPE? 

Best,
Ran

**Comment by maximumko** [comment]
Hi Ran,
Thank you for your rapid reply! I will try it again.
Best, 
Max

**Comment by maximumko** [comment]
Hi Ran,
I applied the cells after qc with Seurat and Cellranger loupe to the pipeline, however the same issue appeared again. For Seurat, I filtered the cells with these thresholds: ` nFeature_RNA > 250 & nFeature_RNA < 12500 & percent.mt < 5 & percent.HB < 3 & nCount_RNA < 100000 & nCount_RNA > 500 & log10GenesPerUMI > 0.80`

Is there any other possible reason leading to this situation?

Best,
Max
